// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTa50wkmuoa0hvsSiusXqJ75_hzDJOLX8',
    appId: '1:365349821682:web:ee42c754f8cb2026fd846b',
    messagingSenderId: '365349821682',
    projectId: 'applist-ffc66',
    authDomain: 'applist-ffc66.firebaseapp.com',
    databaseURL: 'https://applist-ffc66-default-rtdb.firebaseio.com',
    storageBucket: 'applist-ffc66.appspot.com',
    measurementId: 'G-JZMG6ZYJ5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP5S82cYxNywpDU8pox6DtYCLthzYcpkU',
    appId: '1:365349821682:android:b97757e84bb3837efd846b',
    messagingSenderId: '365349821682',
    projectId: 'applist-ffc66',
    databaseURL: 'https://applist-ffc66-default-rtdb.firebaseio.com',
    storageBucket: 'applist-ffc66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjTPcvjY2ZoZRQaUADdD266ro6QGs12LU',
    appId: '1:365349821682:ios:b00f770a679f619dfd846b',
    messagingSenderId: '365349821682',
    projectId: 'applist-ffc66',
    databaseURL: 'https://applist-ffc66-default-rtdb.firebaseio.com',
    storageBucket: 'applist-ffc66.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjTPcvjY2ZoZRQaUADdD266ro6QGs12LU',
    appId: '1:365349821682:ios:b00f770a679f619dfd846b',
    messagingSenderId: '365349821682',
    projectId: 'applist-ffc66',
    databaseURL: 'https://applist-ffc66-default-rtdb.firebaseio.com',
    storageBucket: 'applist-ffc66.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTa50wkmuoa0hvsSiusXqJ75_hzDJOLX8',
    appId: '1:365349821682:web:1fc06581c5573956fd846b',
    messagingSenderId: '365349821682',
    projectId: 'applist-ffc66',
    authDomain: 'applist-ffc66.firebaseapp.com',
    databaseURL: 'https://applist-ffc66-default-rtdb.firebaseio.com',
    storageBucket: 'applist-ffc66.appspot.com',
    measurementId: 'G-BBZ531Y6NB',
  );
}
